Create a database based on a diagram - Pair-programming activity
hajnaloltyan/diagram-database pull request #1
Opened 2023-09-26 21:40 UTC by hajnaloltyan

## Create a database based on a diagram - Pair-programming activity

In this PR my Coding partner and I:

* Created the repo and a file named schema_based_on_diagram.sql
* Implemented the database from the diagram
* Added the FK indexes

2023-09-26 21:57 UTC, MahmoudBakr23 requested changes
Hello TEAM 😃, 

Great work and effort you put into this project so far.

## Highlights 🚀 

There are some excellent points that you have made perfectly. Keep up! 💪
- Well done creating the tables according to the ERD so far
- Descriptive PR and README

However, there is always room for improvement.

> I'd like to remind you that your long hours of work are appreciated. However, the code review process is for improving your code, not criticizing it. 😄

 ## Required Changes ♻️
_Please check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

N/A

Cheers, and Happy coding!👏👨‍💻💻

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-26 21:57 UTC, MahmoudBakr23 commented on schema_based_on_diagram.sql
> +CREATE INDEX invoice_items_treatment_id_idx ON invoice_items(treatment_id);
- [ ] Great job so far creating the indexes. However, you're missing two important ones as per project requirements, please create an index on `medical_histories_has_treatments (medical_history_id)` and on `medical_histories_has_treatments (treatment_id)`

2023-09-27 00:07 UTC, AbayomiOlaoye approved these changes

2023-09-27 00:08 UTC, AbayomiOlaoye approved these changes
## STATUS: APPROVED :green_circle:  

Hi @Team  :wave: :wave:, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![applause](https://user-images.githubusercontent.com/99715640/213818870-485b6c36-1d87-4b93-9a0c-ce2ae86d9a9d.gif)

## Highlights
- Cleanly written code :white_check_mark: 
- Professional repo documentation and Gitflow ✅ 
- Nicely implemented feedback ✅ 
- Great teamwork ✅ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-27 00:21 UTC, merged